### ISSUE TITLE
HTTPX read timeout is set to infinite by default

### ISSUE THREAD

**Issue by ryancausey** [fauna/fauna-python#122]
I traced a hung client down to this following line where it appears if no timeouts are passed, the HTTP read timeout is set to `None`. This, as far as I can tell from the HTTPX docs, means it will never time out.

Line: https://github.com/fauna/fauna-python/blob/main/fauna/client/client.py#LL123C18-L123C18
HTTPX timeout docs: https://www.python-httpx.org/advanced/#timeout-configuration
FQLv10 code that produced the hung client: https://forums.fauna.com/t/fqlv10-comparison-of-objects-never-completes/3652

**Comment by ptpaterson** [comment]
Thanks for the issue, repro information, and bringing this to our attention!

More work is scheduled for the Python driver before GA. An internal issue has been created to track this: BT-3922
